plugins {
    id 'com.android.library' version '8.2.0'
}

android {
    namespace 'com.cyrust.fftoolspromaxnew'
    compileSdk 34

    defaultConfig {
        minSdk 21
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=none"
            }
        }
    }
    buildFeatures {
        prefab true 
    }
    externalNativeBuild {
        cmake {
            path "jni/CMakeLists.txt"
            version = "3.22.1+" 
        }
    }
}

dependencies {
    // Library persis seperti yang dipakai Shizuku terbaru
    implementation 'io.github.vvb2060.ndk:boringssl:20250114'
    implementation 'org.lsposed.libcxx:libcxx:27.0.12077973'
}
