name: Build C++ Native (CMake Murni)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-cpp:
    runs-on: ubuntu-latest
    
    # Targetkan arsitektur 64-bit yang modern
    strategy:
      matrix:
        abi: [arm64-v8a]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile C++ for ${{ matrix.abi }}
        run: |
          # Cari NDK terbaru
          NDK_PATH=$(ls -d $ANDROID_HOME/ndk/* | tail -1)
          echo "Menggunakan NDK: $NDK_PATH"
          
          # Masuk ke folder JNI
          cd jni
          
          # Buat folder build
          BUILD_DIR="build_${{ matrix.abi }}"
          mkdir -p $BUILD_DIR
          cd $BUILD_DIR
          
          # Jalankan CMake (Akan otomatis mengunduh boringssl)
          cmake -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=${{ matrix.abi }} \
                -DANDROID_PLATFORM=android-21 \
                ..
                
          # Jalankan make
          make

      - name: Upload Binary Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ffx-native-bin-${{ matrix.abi }}
          path: jni/build_${{ matrix.abi }}/
          compression-level: 9
